### ISSUE TITLE
Removing listeners

### ISSUE THREAD

**Issue by anonimusprogramus** [alexmacarthur/probaclick#5]
Hi Alex.

I'm using probaclick in dynamically mounted/unmounted components (using riotjs).

Once ProbaClick() called, how's to safely remove ProbaClick's listeners when the parent container got removed? I'm afraid of memory leaks.

Thank you

**Comment by alexmacarthur** [comment]
Apologies for the delay! A `.remove()` method has been added to any instance in v2.0.0:

https://github.com/alexmacarthur/probaclick/releases/tag/v2.0.0

Thanks!
